"""create core tables

Revision ID: 4bb970b491d0
Revises: 
Create Date: 2026-06-24 10:42:59.547245

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb970b491d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('event_title', sa.String(length=512), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_subject', sa.String(length=256), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='new', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_events_event_time'), ['event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)

    op.create_table('raw_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_news_content_hash'), ['content_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_raw_news_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_news_url'), ['url'], unique=False)

    op.create_table('event_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('importance_score', sa.Integer(), nullable=False),
    sa.Column('importance_level', sa.String(length=2), nullable=False),
    sa.Column('affected_industries', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('affected_assets', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('causal_chain', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('positive_factors', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('negative_factors', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('risk_warning', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('importance_score BETWEEN 1 AND 5', name='ck_importance_score_1_5'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_analysis_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_analysis_importance_level'), ['importance_level'], unique=False)

    op.create_table('event_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('raw_news_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_news_id'], ['raw_news.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'raw_news_id', name='uq_event_source_pair')
    )
    with op.batch_alter_table('event_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_sources_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_sources_raw_news_id'), ['raw_news_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_sources_raw_news_id'))
        batch_op.drop_index(batch_op.f('ix_event_sources_event_id'))

    op.drop_table('event_sources')
    with op.batch_alter_table('event_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_analysis_importance_level'))
        batch_op.drop_index(batch_op.f('ix_event_analysis_event_id'))

    op.drop_table('event_analysis')
    with op.batch_alter_table('raw_news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_news_url'))
        batch_op.drop_index(batch_op.f('ix_raw_news_published_at'))
        batch_op.drop_index(batch_op.f('ix_raw_news_content_hash'))

    op.drop_table('raw_news')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_events_event_time'))
        batch_op.drop_index(batch_op.f('ix_events_event_id'))

    op.drop_table('events')
    # ### end Alembic commands ###
